const rankData = [
  {
    id: 54,
    rank: 1,
    name: 'Wii Sports',
    platform: 'Wii',
    year: 2006,
    genre: 'Sports',
    publisher: 'Nintendo',
    northAmericaSales: 41.49,
    europeSales: 29.02,
    japanSales: 3.77,
    otherSales: 8.46,
    globalSales: 82.74,
  },
  {
    id: 15,
    rank: 2,
    name: 'Super Mario Bros.',
    platform: 'NES',
    year: 1985,
    genre: 'Platform',
    publisher: 'Nintendo',
    northAmericaSales: 29.08,
    europeSales: 3.58,
    japanSales: 6.81,
    otherSales: 0.77,
    globalSales: 40.24,
  },
  {
    id: 23,
    rank: 3,
    name: 'Mario Kart Wii',
    platform: 'Wii',
    year: 2008,
    genre: 'Racing',
    publisher: 'Nintendo',
    northAmericaSales: 15.85,
    europeSales: 12.88,
    japanSales: 3.79,
    otherSales: 3.31,
    globalSales: 35.82,
  },
  {
    id: 21,
    rank: 4,
    name: 'Wii Sports Resort',
    platform: 'Wii',
    year: 2009,
    genre: 'Sports',
    publisher: 'Nintendo',
    northAmericaSales: 15.75,
    europeSales: 11.01,
    japanSales: 3.28,
    otherSales: 2.96,
    globalSales: 33,
  },
  {
    id: 24,
    rank: 5,
    name: 'Pokemon Red/Pokemon Blue',
    platform: 'GB',
    year: 1996,
    genre: 'Role-Playing',
    publisher: 'Nintendo',
    northAmericaSales: 11.27,
    europeSales: 8.89,
    japanSales: 10.22,
    otherSales: 1,
    globalSales: 31.37,
  },
  {
    id: 44,
    rank: 6,
    name: 'Tetris',
    platform: 'GB',
    year: 1989,
    genre: 'Puzzle',
    publisher: 'Nintendo',
    northAmericaSales: 23.2,
    europeSales: 2.26,
    japanSales: 4.22,
    otherSales: 0.58,
    globalSales: 30.26,
  },
  {
    id: 47,
    rank: 7,
    name: 'New Super Mario Bros.',
    platform: 'DS',
    year: 2006,
    genre: 'Platform',
    publisher: 'Nintendo',
    northAmericaSales: 11.38,
    europeSales: 9.23,
    japanSales: 6.5,
    otherSales: 2.9,
    globalSales: 30.01,
  },
  {
    id: 46,
    rank: 8,
    name: 'Wii Play',
    platform: 'Wii',
    year: 2006,
    genre: 'Misc',
    publisher: 'Nintendo',
    northAmericaSales: 14.03,
    europeSales: 9.2,
    japanSales: 2.93,
    otherSales: 2.85,
    globalSales: 29.02,
  },
  {
    id: 5,
    rank: 9,
    name: 'New Super Mario Bros. Wii',
    platform: 'Wii',
    year: 2009,
    genre: 'Platform',
    publisher: 'Nintendo',
    northAmericaSales: 14.59,
    europeSales: 7.06,
    japanSales: 4.7,
    otherSales: 2.26,
    globalSales: 28.62,
  },
  {
    id: 22,
    rank: 10,
    name: 'Duck Hunt',
    platform: 'NES',
    year: 1984,
    genre: 'Shooter',
    publisher: 'Nintendo',
    northAmericaSales: 26.93,
    europeSales: 0.63,
    japanSales: 0.28,
    otherSales: 0.47,
    globalSales: 28.31,
  },
];

export default rankData;
